services:
  - type: web
    name: jackett-stremio
    env: docker
    plan: free
    disk:
      name: jackett-data
      mountPath: /config
      sizeGB: 1
    dockerCommand: ""
    dockerImage: linuxserver/jackett:latest
    envVars:
      - key: TZ
        value: Europe/Bratislava
    ports:
      - port: 9117
        nodePort: 9117
