services:
  - type: web
    name: jackett-stremio
    env: docker
    plan: free
    disk:
      name: jackett-data
      mountPath: /config
      sizeGB: 1
    envVars:
      - key: TZ
        value: Europe/Bratislava
    dockerImage: linuxserver/jackett:latest
    port: 9117
